server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**,/api/v1/admin/**
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/catalog/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/inventory/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/orders/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
    secret: atlas-platform-jwt-secret-at-least-32-bytes-long
